baseURL = "https://edu.jonathan-kaplan.eu"
languageCode = "en"
title = "Jonathan Kaplan"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true

[pagination]
pagerSize = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
