navbar_title = 'Jonathan Kaplan'
footer = "Copyright © 2025 Jonathan Kaplan"
author = "Jonathan Kaplan"
color_scheme = "light"

enable_zooming_js = false
enable_header_anchor = false
enable_toc = false
enable_site_search = false
enable_math = false

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Collapsible Menu
enable_collapsible_toc = false
enable_collapsible_changelogs = false

[list_layout]
enable_group_by_year = true
enable_show_date = false
enable_pagination = false

# syntax highlight settings
[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

    [syntax_highlight.builtin]
    enable_code_copy = true

    [syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = false
