[[navbar]]
  identifier = "Publications"
  name = "Publications"
  url = "/fr/publication/"
  weight = 10
  [[navbar]]
    identifier = "Book"
    name = "Livre"
    url = "/fr/publication/book/"
    parent = "Publications"
    weight = 11
  [[navbar]]
    identifier = "Cercles d{'}étude"
    name = "Cercles d’étude au service d’une intelligence collective"
    url = "/fr/publication/sc/"
    parent = "Publications"
    weight = 12
[[navbar]]
  identifier = "Posts"
  name = "Nouvelles"
  url = "/fr/post/"
  weight = 20
